Numpy tutorial

In [3]:
import numpy as np

In [10]:
myarr = np.array([[3,6,34,65 ,np.int64]])

In [5]:
myarr

array([[3, 6, 34, 65, <class 'numpy.int8'>]], dtype=object)

In [7]:
myarr[0,2]

34

In [11]:
myarr.dtype

dtype('O')

In [8]:
myarr.shape

(1, 5)

In [13]:
# Array creation

In [14]:
listarray= np.array([[1,2,3] ,[3,5,6],[9,5,4]])

In [15]:
listarray

array([[1, 2, 3],
       [3, 5, 6],
       [9, 5, 4]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [23]:
listarray[1,1]

57

In [22]:
listarray[1,1]=57

In [24]:
zeros= np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
zeros.shape

(2, 5)

In [31]:
rng= np.arange(15)

In [32]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
lspace=np.linspace(1,5,12)

In [34]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [36]:
emp=np.empty((4,6))

In [37]:
emp

array([[6.70755236e-294, 1.58933095e-290, 2.97456491e-316,
        2.27653662e-291, 1.03872656e-291, 2.00307969e-291],
       [2.00320202e-291, 1.58348874e-290, 1.59052486e-290,
        1.58358660e-290, 1.03669597e-291, 1.03672655e-291],
       [1.03707518e-291, 1.03713634e-291, 1.03678772e-291,
        1.59039764e-290, 1.03681830e-291, 1.03336262e-291],
       [1.03342990e-291,             nan, 3.92571156e-312,
        1.58343001e-290,             nan, 1.12646967e-321]])

In [40]:
smp=np.empty(4)

smp

In [41]:
smp

array([1.54398111e-307, 8.21483987e-308, 1.58687467e-290, 3.05567394e-312])

In [42]:
emp_like=np.empty_like(smp)

In [43]:
emp_like

array([1.54398111e-307, 8.21483987e-308, 1.58687467e-290, 3.05567394e-312])

In [44]:
ide =np.identity(8)

In [45]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
ide.reshape(4,16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
rng.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
arr=np.arange(64)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [55]:
arr.reshape(4,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [57]:
arr =arr.ravel()

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [59]:
arr.shape

(64,)

In [60]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [63]:
arr=np.array(x)

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
arr.sum(axis=0)

array([12,  8,  9])

In [66]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [67]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [68]:
# transpose


In [69]:
arr.flat

In [70]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [71]:
arr.ndim

2

In [73]:
arr.nbytes

36

In [74]:
arr.argmax()

6

In [75]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [76]:
# argsort gives index of sorted arrays

In [77]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [78]:
# axis = 0 mtlb columns ma sbse bda konse index ma ha

In [79]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [80]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [82]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [84]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [90]:
arr2 = np.array([[1, 4, 7],[2, 5, 1],[3, 6, 0]])

In [91]:
arr2

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [92]:
arr2+arr

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [94]:
arr * arr2

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [95]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [97]:
np.where(arr>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [98]:
import sys

In [99]:
# showing ke laise numpy se aap km memory ma he bna skte ho

In [100]:
py_arr=[0,4,55,2]

In [105]:
np_arr=np.array(py_arr)

In [107]:
sys.getsizeof(1)*len(py_arr)

64

In [108]:
np_arr.itemsize * np_arr.size

16