Numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,34,65 ,np.int64]])

In [3]:
myarr

array([[3, 6, 34, 65, <class 'numpy.int64'>]], dtype=object)

In [4]:
myarr[0,2]

34

In [5]:
myarr.dtype

dtype('O')

In [6]:
myarr.shape

(1, 5)

In [7]:
# Array creation

In [8]:
listarray= np.array([[1,2,3] ,[3,5,6],[9,5,4]])

In [9]:
listarray

array([[1, 2, 3],
       [3, 5, 6],
       [9, 5, 4]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
listarray[1,1]

5

In [14]:
listarray[1,1]=57

In [15]:
zeros= np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
rng= np.arange(0,15,0.5) 

In [20]:
rng

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [21]:
rng2=np.arange(21)
# 20 tk he print krega

In [22]:
rng2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [23]:
lspace=np.linspace(1,5,12)

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp=np.empty((4,6))
# gives the 4,6 2d array with random elements

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521646e-306, 4.45058910e-308, 1.78019082e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.02360935e-306, 1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        9.45699680e-308, 1.11258854e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306, 7.56602523e-307, 1.29061821e-306]])

In [27]:
smp=np.empty(4)

smp

In [28]:
smp

array([2.12199579e-314, 6.95208261e-310, 5.96831300e-321, 3.79442416e-321])

In [29]:
emp_like=np.empty_like(smp)
# copies the size of array you declared before

In [30]:
emp_like

array([2.12199579e-314, 6.95208261e-310, 5.96831300e-321, 3.79442416e-321])

In [31]:
ide =np.identity(8)
# gives identity matrix

In [32]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
ide.reshape(4,16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
rng.ravel() 
# kise bhi array ko 1D array bna deta ha

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [35]:
arr=np.arange(64)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [37]:
arr.reshape(4,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [38]:
arr =arr.ravel()

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [40]:
arr.shape

(64,)

In [41]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [42]:
arr=np.array(x)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.sum(axis=0)

array([12,  8,  9])

In [45]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [46]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
# transpose

In [74]:
arr.flat()

TypeError: 'numpy.flatiter' object is not callable

In [49]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [50]:
arr.ndim

2

In [51]:
arr.nbytes

36

In [52]:
arr.argmax()

6

In [53]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [54]:
# argsort gives index of sorted arrays

In [55]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [56]:
# axis = 0 mtlb columns ma sbse bda konse index ma ha

In [57]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [58]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [59]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [60]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [61]:
arr2 = np.array([[1, 4, 7],[2, 5, 1],[3, 6, 0]])

In [62]:
arr2

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [63]:
arr2+arr

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [64]:
arr * arr2

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [65]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [68]:
import sys

In [69]:
# showing ke laise numpy se aap km memory ma he bna skte ho

In [70]:
py_arr=[0,4,55,2]

In [71]:
np_arr=np.array(py_arr)

In [72]:
sys.getsizeof(1)*len(py_arr)

112

In [73]:
np_arr.itemsize * np_arr.size

16